[package]
name = "stemforge"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = ["tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mdns-sd = "0.10"
tauri-plugin-notification = "2.3.3"
# âŒ tauri-plugin-updater removed

[features]
custom-protocol = ["tauri/custom-protocol"]
